### PR TITLE
Update DockManager.cs

### PR DESCRIPTION
**Pull request by CombinEC-R**
Check if the Actor can reach the dock and Skips it when it cannot.

### CODE REVIEW

**Comment by CombinEC-R** [comment]
Forgott to remove the Game.Debug, but thats no issue! 👍

**Comment by CombinEC-R** [comment]
Second one works! removed the debug and added a null-check.

**Comment by GraionDilach** [comment]
This has a lot of formatting errors and it can't even compile on Travis.

**Comment by CombinEC-R** [comment]
y i messed up! :|
need to redo it and try again if wanted, basicly a pathing check

**Pull request closed without merging**
